### ISSUE TITLE
The stack gets stuck on CREATE_IN_PROGRESS

### ISSUE THREAD

**Issue by Jim-Bar** [m-chandler/factorio-spot-pricing#10]
When creating the stack with default parameters, region Paris, and with a key pair, the stack never reaches the state `RUNNING` because of the resource `EcsService`:

EcsService | arn:aws:ecs:eu-west-3:384881610529:service/factorio | AWS::ECS::Service | CREATE_IN_PROGRESS | Resource creation Initiated | 
-- | -- | -- | -- | -- | --

I waited for about one hour. Thoughts?

**Comment by m-chandler** [comment]
@Jim-Bar the issue is that Paris is quite a new region, and the `m3.medium` instance type that the stack defaults to is not available in this region.

The reason for using the older instance by default, is because it's *very cheap* in regions that have it.

I would suggest that you use an `m5.large`. This will probably run you about 3-4c/hr. You can try with a smaller instance type, but I wouldn't recommend it. The compute / memory on the smaller instances is fine but I've had network issues with certain friends.

![image](https://user-images.githubusercontent.com/2039337/66261774-f17df880-e816-11e9-83f7-bfc1d64367dd.png)

Trying this now... and will update readme if it works okay.

**Comment by m-chandler** [comment]
Added some more detail to readme. Hope this makes sense and helps.
