### ISSUE TITLE
Space Age Mods?

### ISSUE THREAD

**Issue by robertmassaioli** [m-chandler/factorio-spot-pricing#40]
I just had a quick try using the "latest" docker tag and my automatically updated Steam version of Factorio was not able to connect so well without Space Age to the docker factorio that seems to include it in version 2 by default.

Anybody else having that issue? What did you do to resolve it? I think the mods are paid and I'm not sure how to use this with version 2 of Factorio.

If somebody knows a way, it would be good to update the readme. Maybe I need to configure Mods somehow in the docker image to remove the SpaceAge mods?

**Comment by m-chandler** [comment]
Hmmm... seems it's already reported here: https://github.com/factoriotools/factorio-docker/issues/510.

Seems you can edit mod-list.json to disable the space age mods, then it should work. You've been tinkering around the config / saves so you can make it work similar to uploading a new save. Although I understand it's possibly not straight forward for all users.

Probably best to wait to see how the factoriotools team handle the issue. If they implement an environment variable then we can just tap into that, rather than trying to roll our own solution.

**Comment by fank** [comment]
@m-chandler `DLC_SPACE_AGE` `true` by default.

**Comment by robertmassaioli** [comment]
Thankyou! I'll incorporate this in short order! But hopefully someone else can get there first because it will take me about a day.

**Comment by robertmassaioli** [comment]
Okay, I've added support AND tested that it works in a new stack: https://github.com/robertmassaioli/factorio-multi-server-spot-pricing/commit/5c3988a78b6aec5725674d6813f185c71084a5be

I'll be submitting a fix here soon.

**Comment by robertmassaioli** [comment]
And there we go: https://github.com/m-chandler/factorio-spot-pricing/pull/41

Let me know if that works for you!
